{{- if and (.Values.postgresqlCluster.enabled) (.Values.postgresqlCluster.objectStorage.s3.customAccessKeys.use) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "grafana-app.labels" . | nindent 4 }}
  name: {{ .Values.postgresqlCluster.name }}-access-keys
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ACCESS_KEY_ID: "{{ .Values.postgresqlCluster.objectStorage.s3.customAccessKeys.accessKeyId }}"
  SECRET_ACCESS_KEY: "{{ .Values.postgresqlCluster.objectStorage.s3.customAccessKeys.secretAccessKey }}"
{{- end }}
