{{- if and (.Values.postgresqlCluster.enabled) (and (.Values.postgresqlCluster.objectStorage.s3.secretAccessKey) (.Values.postgresqlCluster.objectStorage.s3.accessKeyId)) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ .Values.postgresqlCluster.name }}-access-keys
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ACCESS_KEY_ID: "{{ .Values.postgresqlCluster.objectStorage.s3.accessKeyId }}"
  SECRET_ACCESS_KEY: "{{ .Values.postgresqlCluster.objectStorage.s3.secretAccessKey }}"
{{- end }}
