{{- if and (.Values.postgresqlCluster.enabled) (.Values.postgresqlCluster.backup.enabled) }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ .Values.postgresqlCluster.name }}-hourly-backup
  namespace:  {{ .Release.Namespace }}
spec:
# At 0 minute and 0 second of every hour
  schedule: {{ .Values.postgresqlCluster.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.postgresqlCluster.name }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}
